### ISSUE TITLE
Solicitud nuevo integrante

### ISSUE THREAD

**Issue by mamanidario19** [gus0117/devtech-podcast-web#1]
## Presentación
Hola compañero! soy Dario te escribo para que me permitas agregar mi tarjeta en tu proyecto.

![image](https://media3.giphy.com/media/ZVik7pBtu9dNS/giphy.gif?cid=ecf05e47mab7sns7v0vihufesxo2wv4vkcdxe099wjnyvrjx&rid=giphy.gif&ct=g)

## Modificaciones futuras:
 * Agregar imagen de avatar.
 * Modificar index.html con mi descripción.
## Previsualización
![image](https://user-images.githubusercontent.com/32744941/178361136-e888ec93-c7e2-446e-9478-d2abf0ae2cb1.png)
 
Espero tu aprobación! saludos! 🙇‍♂️

**Comment by gus0117** [comment]
## Solicitud aprobada #1

Hola Darío, muy interesante tu propuesta, podes realizar modificaciones en la **tarjeta 2**.

Saludos!
