### ISSUE TITLE
Solicitud de incorporación como miembro del equipo del podcast DevTech

### ISSUE THREAD

**Issue by alecio87** [gus0117/devtech-podcast-web#2]
## Solicitud de incorporación.

Hola @gus0117  soy Emanuel Ibañes, te solicito incorporarme como miembro del equipo al proyecto 😁😁.
![image](https://media.giphy.com/media/f7omQNmgiyjj5sffvZ/giphy.gif)

### Modificaciones que propongo

- Agregaré un nuevo asset para mi avatar de Avatar Maker y una descripción mia.
- Modificare una tarjeta para que quede tal cual así:

![image](https://user-images.githubusercontent.com/21963028/178361959-73208135-a844-434d-ac9a-a1b947539a07.png)

### Enlaces
- [Extención de google chrome](https://chrome.google.com/webstore/detail/avatar-maker/ofknlbikfofijlcjkfcihomkedmchfbn)

**Comment by gus0117** [comment]
## Solicitud Aprobada #2

Hola Emanuel, me parece bien tu propuesta. Por favor, agrega los cambios en la **tarjeta 3**.

Saludos!
